### PR TITLE
Sybase IQ JDBC Driver Fixes

### PR DESCRIPTION
**Pull request by shantstepanian**
I had submitted the original Sybase IQ implementation some time back. But there were some flaws that I recently learned about and now fixed

1) The original class SybaseIQDatabaseConnector was intended for the [JConnect driver](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc01776.1604/doc/html/san1357754912881.html)

Originally, I thought that it did not support catalog + schemas, but it does. Hence, I removed those clauses from the existing code and added the correct ROUTINES and VIEWS sqls

2) You can also connect to Sybase IQ via their [ODBC Driver](http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc39500.1510/html/iqicghp/iqicghp119.htm). This driver behaves a bit differently, as it _doesn't_ support catalogs. As a result, I had to update that code accordingly

3) Originally, I used jdbc:sybase as the JDBC URL prefix for IQ. However, that conflicts with Sybase ASE. While Sybase ASE and IQ can be connected to with the same driver, they have different metadata tables; hence, I don't think we should allow connections using that in SchemaCrawler. I'm open to your opinion on this

As we have two different drivers, I provided two DatabaseConnector implementations

Let me know what you think; I'm open to revisions here. No rush on this

### CODE REVIEW

**Comment by sualeh** [comment]
Shant, thanks, I will take a look at this code. Are you using the [JDBC-ODBC bridge](http://docs.oracle.com/javase/7/docs/technotes/guides/jdbc/bridge.html)?

**Comment by shantstepanian** [comment]
No, not the JDBC-ODBC bridge

The JConnect driver is com.sybase.jdbc4.jdbc.SybDriver (or jdbc3 or jdbc2 depending on the version)

The ODBC drivers are listed in the table on this page: http://scn.sap.com/community/sql-anywhere/blog/2014/05/02/connecting-to-sql-anywhere-using-jdbc, any of the ianywhere.ml.jdbcodbc.* drivers or the sybase.jdbc.sqlanywhere.IDriver driver

**Comment by sualeh** [comment]
I will not be able to use the same `DatabaseServerType`, since the command-line option `-server` needs a unique server type name. Also, SchemaCrawler cannot match the `DatabaseConnector` if a URL pattern is not provided. This reduces the usefulness of the changes, since they can only be used programatically. I will rework your code, and then commit the changes.

**Comment by shantstepanian** [comment]
I use this programmatically by directly instantiating the class, so I'm fine with that.

I do have the URL strings for the ODBC driver; I will send that tomorrow.

The conflict is on the jconnect driver, since both ase and iq use it and their urls match. Potentially the raw jdbc code works the same; just that the custom information schema views would be different. Fyi I haven't contributed any ASE code because it seems to work a bit differently.

**Comment by shantstepanian** [comment]
Actually, I see the driver to url mappings on the page I linked earlier: https://blogs.sap.com/2014/05/02/connecting-to-sql-anywhere-using-jdbc-2/

|Driver|URL|Connector|
|sybase.jdbc.sqlanywhere.IDriver|jdbc:sqlanywhere:|SybaseIQOdbcDatabaseConnector|
|ianywhere.ml.jdbcodbc.jdbc3.IDriver|jdbc:ianywhere:|SybaseIQOdbcDatabaseConnector|
|com.sybase.jdbc3.jdbc.SybDriver|jdbc:sybase:Tds:|SybaseIQDatabaseConnector - that works against IQ or ASE, but we don't have any ASE code in SchemaCrawler currently|

**Comment by sualeh** [comment]
This issue was moved to sualeh/SchemaCrawler-Sybase#1

**Pull request closed without merging**
