### PR TITLE
Shell script: made it totally path relative

### PR DESCRIPTION
**Pull request by David-Guillot**

### CODE REVIEW

**Comment by sualeh** [comment]
Thanks for the patch, David. Please make this available as a [GitHub Gist](https://gist.github.com/), and I will link to it from the SchemaCrawler website. Please send me the Gist URL.

**Comment by David-Guillot** [comment]
@sualeh I don't really see the point of not merging this PR if you agree with the code, but here it is: https://gist.github.com/David-Guillot/dd53227141fd62ff5db6ef23c929f7b1

**Comment by sualeh** [comment]
@David-Guillot - don't misunderstand me - I appreciate your contribution. Please see https://github.com/sualeh/SchemaCrawler/issues/115 for an example of why I am hesitant to merge your PR, but rather have it as a Gist.

**Comment by David-Guillot** [comment]
Ok @sualeh I understand, I didn't think of OS compatibility :/

**Pull request closed without merging**
